---
object_type: class
version: 1.0
object:
  attributes:
    description: 
    display_name: 
    name: DELETEME
    type: 
    inherits: 
    visibility: 
    owner: 
  schema:
  - field:
      aetype: state
      name: test_state
      display_name: 
      datatype: string
      priority: 1
      owner: 
      default_value: "/some/path"
      substitute: true
      message: create
      visibility: 
      collect: ''
      scope: 
      description: 
      condition: 
      on_entry: update_provision_status(status=>'hi')
      on_exit: ''
      on_error: ''
      max_retries: '100'
      max_time: 
